{{- range $key, $val := .Values.apps }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: edu30
spec:
  project: {{ $val.project | default $.Values.default.app.project }}

  source:
    path: charts/{{ $key }}
    repoURL: "https://github.com/shclub/edu14-1.git"
    targetRevision: {{ $val.targetRevision | default $.Values.default.app.targetRevision }}
    helm:
      valueFiles:
        - values.yaml

  destination:
    namespace: {{ $val.namespace | default $.Values.default.app.namespace }}
    server: "https://kubernetes.default.svc"

{{- if $val.autoSync | default $.Values.default.app.autoSync }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=false  
{{- end }}      
---      
{{- end }}
{{- end }}
